name: "Copilot Setup Steps"

on:
  workflow_dispatch:

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install devbox + Nix + devbox.json packages
        uses: jetify-com/devbox-install-action@v0.12.0

      - name: Sanity check
        run: devbox list
